language: node_js
node_js:
  - 'node'
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
before_install:
  - sudo apt-get install --no-install-recommends -y bsdtar
script:
  - npm run dist
